version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: cival-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - cival-network

  dashboard:
    build: .
    container_name: cival-dashboard
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TRADING_API_URL=http://trading-api:3001
      - MCP_API_URL=http://mcp-server:3000
      - VAULT_API_URL=http://vault-service:3002
    depends_on:
      - redis
      - trading-api
      - mcp-server
    networks:
      - cival-network

  trading-api:
    build:
      context: ./services/trading-api
    container_name: cival-trading-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/trading
    depends_on:
      - redis
      - postgres
    networks:
      - cival-network

  mcp-server:
    build:
      context: ./services/mcp-server
    container_name: cival-mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cival-network

  vault-service:
    build:
      context: ./services/vault-service
    container_name: cival-vault-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VAULT_API_KEY=${VAULT_API_KEY}
    depends_on:
      - redis
    networks:
      - cival-network

  postgres:
    image: postgres:15
    container_name: cival-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cival-network

  visualization-service:
    build:
      context: ./services/visualization
    container_name: cival-visualization
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cival-network

networks:
  cival-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: 